TMS/TMS/Presentation/Panel/Areas/Administrator/Controllers/KullaniciController.cs
using System;
using System.Web.Mvc;
using TMS.Core.Lib;
using TMS.Core.Service;
using TMS.View.Genel;
namespace TMS.Panel.Web.Areas.Administrator.Controllers
{
    public class KullaniciController : AdministratorBaseController
    {
        private KullaniciService KullaniciService = new KullaniciService();
        public KullaniciController()
        {
        }
        public ActionResult Index()
        {
            TMS.View.Administrator.Kullanici Model = new TMS.View.Administrator.Kullanici();
            Model.AktifKayit = new TMS.Core.Data.Kullanici();
            Model.KullaniciListesi = KullaniciService.KullaniciListesiGetir();
            return View(Model);
        }

        [HttpPost]
        public ActionResult Index(TMS.View.Administrator.Kullanici Model, FormCollection Frm)
        {
            Model.KullaniciListesi = KullaniciService.KullaniciListesiGetir();
            return View(Model);
        }

        public ActionResult Delete(int id)
        {
            TMS.View.Administrator.Kullanici Model = new TMS.View.Administrator.Kullanici();
            var Aktif = KullaniciService.GetById(id);
            if (Aktif != null)
            {
                try
                {
                    KullaniciService.Delete(Aktif);
                    KullaniciService.Commit();
                    Model.IslemMesaj.Visible = true;
                    Model.IslemMesaj.Tip = IslemMesajTip.Basarili;
                    Model.IslemMesaj.Baslik = "Silme İşlemleri";
                    Model.IslemMesaj.Mesaj = "Başarıyla Silindi.";

                }
                catch (Exception)
                {
                    Model.IslemMesaj.Visible = true;
                    Model.IslemMesaj.Tip = IslemMesajTip.Hata;
                    Model.IslemMesaj.Baslik = "Silme İşlemleri";
                    Model.IslemMesaj.Mesaj = "Hata Oluştu.";
                }
            }
            else
            {
                Model.IslemMesaj.Visible = true;
                Model.IslemMesaj.Tip = IslemMesajTip.Hata;
                Model.IslemMesaj.Baslik = "Silme İşlemleri";
                Model.IslemMesaj.Mesaj = "Bulunamadı";
            }
            return RedirectToAction("Index", "Kullanici", Model);
        }
        public ActionResult Edit(int id)
        {
            TMS.View.Administrator.Kullanici Model = new TMS.View.Administrator.Kullanici();
            Model.AktifKayit = KullaniciService.GetById(id);
            return View(Model);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(TMS.View.Administrator.Kullanici Model, FormCollection Frm)
        {
            switch (Request.Form["BtnIslem"])
            {
                case "Kaydet":
                    {
                        if (ModelState.IsValid)
                        {
                            try
                            {
                                Model.IslemMesaj.Visible = true;
                                Model.IslemMesaj.Tip = IslemMesajTip.Basarili;
                                Model.IslemMesaj.Baslik = "Kullanıcı İşlemleri";

                                if (Model.AktifKayit.No == 0)
                                {
                                    KullaniciService.Create(Model.AktifKayit);
                                    Model.IslemMesaj.Mesaj = "Kullanıcı Başarıyla Eklendi.";
                                }
                                else
                                {
                                    var Nesne = KullaniciService.GetById(Model.AktifKayit.No);
                                    Nesne.Ad = Model.AktifKayit.Ad;
                                    Nesne.Soyad = Model.AktifKayit.Ad;
                                    Nesne.Mail = Model.AktifKayit.Mail;
                                    KullaniciService.Update(Model.AktifKayit);
                                    Model.IslemMesaj.Mesaj = "Kullanıcı Başarıyla Güncellendi.";
                                }
                                KullaniciService.Commit();
                                Model.KullaniciListesi = KullaniciService.KullaniciListesiGetir();
                                return View("Index", Model);
                            }
                            catch (Exception ex)
                            {
                                Model.IslemMesaj.Visible = true;
                                Model.IslemMesaj.Tip = IslemMesajTip.Hata;
                                Model.IslemMesaj.Baslik = "Kullanıcı İşlemleri";
                                Model.IslemMesaj.Mesaj = "Hata! " + ex.Message;
                                return View(Model);
                            }
                        }
                        else
                        {
                            Model.IslemMesaj.Visible = true;
                            Model.IslemMesaj.Tip = IslemMesajTip.Hata;
                            Model.IslemMesaj.Baslik = "Kullanıcı İşlemleri";
                            Model.IslemMesaj.Mesaj = "Hatalar :<br>" + ModelState.HataListesi().ListToString("<br>");
                            return View(Model);
                        }
                    }
                case "İptal Et":
                    {
                        Model.KullaniciListesi = KullaniciService.KullaniciListesiGetir();
                        return View("Index", Model);
                    }
                default:
                    break;
            }
            return View(Model);
        }
        public ActionResult Create()
        {
            TMS.View.Administrator.Kullanici Model = new TMS.View.Administrator.Kullanici();
            Model.AktifKayit = new TMS.Core.Data.Kullanici();
            Model.AktifKayit.Tarih = DateTime.Now;
            Model.AktifKayit.Durum = (short)Durum.Aktif;
            return View("Edit", Model);
        }
    }
}

TMS/TMS/Presentation/Panel/Areas/Kullanici/Controllers/AnasayfaController.cs
using TMS.Core.Service;
using TMS.Panel.Web.Code;
using System.Linq;
using System.Web.Mvc;
using System.Collections.Generic;

namespace TMS.Panel.Web.Areas.Kullanici.Controllers
{
    public class AnasayfaController : KullaniciBaseController
    {
        private UsersService UsersService = new UsersService();

        private UserBildirimService UserBildirimService = new UserBildirimService();
        private UserOneriService UserOneriService = new UserOneriService();
        private TokenService TokenService = new TokenService();
        private SiparisService SiparisService = new SiparisService();

        [Compress]
        [PageGuide]
        public ActionResult Index()
        {
            SifreDegistirmeLayoutAyarla("~/Areas/Kullanici/Views/Shared/_Layout.cshtml");
            TMS.View.Kullanici.Anasayfa Model = new TMS.View.Kullanici.Anasayfa();
            Model.User = UsersService.Get(x => x.UserId == User.UserId);
            Model.UserBildirimListesi = UserBildirimService.UserGelenBildirimListesiGetir(User.UserId).Where(x => !x.UserBildirim.OkunmaDurum).ToList();
            Model.UserOneriListesi = UserOneriService.UserGelenOneriListesiGetir(User.UserId);
            Model.UserLogListesi = LogService.GetMany(x => x.UserNo == User.UserId && !((int)x.Tip == (int)TMS.View.Genel.LogTip.Giris || (int)x.Tip == (int)TMS.View.Genel.LogTip.Cikis)).OrderByDescending(x => x.Date).Take(5).ToList();
            var TokenListesi = TokenService.GetMany(x => x.UserNo == this.User.UserId);
            Model.TokenSayisi = TokenListesi.Count();
            List<int> TokenNoListesi = TokenListesi.Select(x => x.No).Distinct().ToList();
            Model.SiparisSayisi = SiparisService.GetMany(x => TokenNoListesi.Contains((int)x.KaynakTokenNo)).Count();
            return View(Model);
        }


        [Compress]
        public ActionResult YapimAsamasinda()
        {
            return View();
        }
    }
}

TMS/TMS/Presentation/Panel/Areas/Kullanici/Controllers/AyarlarController.cs
using TMS.Core.Lib;
using TMS.Core.Service;
using TMS.View.Genel;
using System.Web.Mvc;

namespace TMS.Panel.Web.Areas.Kullanici.Controllers
{
    public class AyarlarController : KullaniciBaseController
    {
        private readonly UsersService UsersService = new UsersService();
        private readonly KullaniciService KullaniciService = new KullaniciService();
        public AyarlarController()
        {
            MesajBaslikText = "Ayarlar İşlemleri";
            MesajGuncellemeText = "Ayarlar Başarıyla Güncellendi";
            MesajEklemeText = "Ayarlar Başarıyla Eklendi.";
            MesajSilText = "Ayarlar Başarıyla Silindi.";
            MesajBulunamadiText = "Ayarlar Başarıyla Silindi.";
            MesajHataText = "Hata Oluştu.";
            MesajZatenKayitliText = "Bu Ayarlar Zaten Kayıtlı";
        }
    }
}

TMS/TMS/Presentation/Panel/Areas/Kullanici/Controllers/BaseController.cs
using TMS.Core.Service;
using TMS.Panel.Web.Code.Security;
using TMS.View.Genel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace TMS.Panel.Web.Areas.Kullanici.Controllers
{
    [ProfilFilter]
    public class BaseController : TMS.Panel.Web.Controllers.BaseController
    {

        public Core.Service.IlService IlService { get; set; } = new Core.Service.IlService();

        private UserBildirimService UserBildirimService = new UserBildirimService();
        private UsersService UsersService = new UsersService();
        private KullaniciService KullaniciService = new KullaniciService();



        protected virtual new CustomPrincipal User
        {
            get { return HttpContext.User as CustomPrincipal; }
        }
        public string MesajBaslikText { get; set; } = "";
        public string MesajGuncellemeText { get; set; } = "";
        public string MesajEklemeText { get; set; } = "";

        public string MesajSilText { get; set; } = "";
        public string MesajBulunamadiText { get; set; } = "";
        public string MesajHataText { get; set; } = ".";

        public string MesajZatenKayitliText { get; set; } = "";

        public List<Select2Item> OgrenmeAlaniListesi { get; set; }

        public BaseController()
        {

        }

        public JsonResult IlEkle(string Ifade)
        {
            Select2Item Sonuc = new Select2Item();
            if (!string.IsNullOrEmpty(Ifade))
            {
                var Nesne = IlService.Get(x => x.Ad == Ifade);
                if (Nesne == null)
                {
                    Nesne = new Core.Data.Il()
                    {
                        Ad = Ifade
                    };
                    IlService.Create(Nesne);
                    IlService.Commit();
                }
                Sonuc.id = Nesne.No;
                Sonuc.text = Nesne.Ad;
            }
            return Json(new { Sonuc }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult IlDegerGetir(string id)
        {
            Select2Item Sonuc = new Select2Item();
            if (!string.IsNullOrEmpty(id))
            {
                int No = System.Convert.ToInt32(id);
                var Nesne = IlService.Get(x => x.No == No);
                if (Nesne != null)
                {
                    Sonuc.id = Nesne.No;
                    Sonuc.text = Nesne.Ad;
                }
            }
            return Json(new { Sonuc }, JsonRequestBehavior.AllowGet);
        }



        [HttpPost]
        public JsonResult IlListesiGetir(string term)
        {
            List<Select2Item> Sonuc = IlService.GetMany(m => (term == "" || m.Ad.ToLower().Contains(term.ToLower()))).Select(Snc =>
                    new Select2Item()
                    {
                        id = Snc.No,
                        text = Snc.Ad
                    }
                ).ToList();
            return Json(new { Sonuc }, JsonRequestBehavior.AllowGet);
        }
    }
}

TMS/TMS/Presentation/Panel/Areas/Kullanici/Controllers/DosyaYonetimController.cs
using TMS.Core.Lib;
using System;
using System.IO;
using System.Web;
using System.Web.Mvc;
namespace TMS.Panel.Web.Areas.Kullanici.Controllers
{
    public class DosyaYonetimController : KullaniciBaseController
    {
        [HttpPost]
        public ActionResult DosyaYukle()
        {
            TMS.Core.Lib.IslemDurum IslemSonuc = new Core.Lib.IslemDurum() { Durum = false, Deger = null, Tip = Core.Lib.IslemDurum.IslemMesajTip.Uyari, Hata = null, Mesaj = "" };
            string DizinUrlPath = "~/Content/Dosya/";
            string DizinPath = Server.MapPath(DizinUrlPath);
            DirectoryInfo DizinBilgi = new DirectoryInfo(DizinPath);
            if (!DizinBilgi.Exists) { DizinBilgi.Create(); }
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];
                        string fname;
                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            fname = testfiles[testfiles.Length - 1];
                        }
                        else
                        {
                            fname = file.FileName;
                        }
                        //fname = string.Format("Dosya_{0}_{1}", DateTime.Now.ToString().Replace(" ", "___").Replace(".", "_").Replace(":", "__"), fname);
                        string ServerFileName = $"~/Content/Dosya/User/{User.UserId}/{Guid.NewGuid().ToString()}_{fname.TrkToEng().Replace(" ", "").ToLower()}";
                        string ServerFile = Server.MapPath(ServerFileName);
                        var FileBilgi = new System.IO.FileInfo(ServerFile);
                        if (!FileBilgi.Directory.Exists)
                        {
                            FileBilgi.Directory.Create();
                        }
                        file.SaveAs(ServerFile);
                        IslemSonuc.Durum = true;
                        IslemSonuc.Mesaj = "Dosya Başarıyla Yüklendi.";
                        IslemSonuc.Tip = Core.Lib.IslemDurum.IslemMesajTip.Basarili;
                        IslemSonuc.Deger = ServerFileName;
                    }
                }
                catch (Exception Hata)
                {
                    IslemSonuc.Durum = true;
                    IslemSonuc.Mesaj = "Dosya Yüklenemedi Hata Oluştu. Ayrıntılar : " + Hata.Message;
                    IslemSonuc.Tip = Core.Lib.IslemDurum.IslemMesajTip.Hata;
                    IslemSonuc.Deger = null;
                    IslemSonuc.Hata = Hata;
                }
            }
            else
            {
                IslemSonuc.Durum = true;
                IslemSonuc.Mesaj = "Dosya Yok.";
                IslemSonuc.Tip = Core.Lib.IslemDurum.IslemMesajTip.Hata;
                IslemSonuc.Deger = null;
                IslemSonuc.Hata = null;
            }
            return Json(IslemSonuc, JsonRequestBehavior.AllowGet);
        }
    }
}

TMS/TMS/Presentation/Panel/Areas/Kullanici/Controllers/FileController.cs
using ElFinder;
using System.IO;
using System.Web.Mvc;

namespace TMS.Panel.Web.Areas.Kullanici.Controllers
{
    public partial class FileController : Controller
    {
        public virtual ActionResult Index(string folder, string subFolder)
        {
            FileSystemDriver driver = new FileSystemDriver();
            var root = new Root(
                    new DirectoryInfo(Server.MapPath("~/" + folder)),
                    "http://" + Request.Url.Authority + "/" + folder)
            {
                // Sample using ASP.NET built in Membership functionality...
                // Only the super user can READ (download files) & WRITE (create folders/files/upload files).
                // Other users can only READ (download files)
                // IsReadOnly = !User.IsInRole(AccountController.SuperUser)
                IsReadOnly = false,
                Alias = "Files", // Beautiful name given to the root/home folder
                MaxUploadSizeInKb = 10000 // Limit imposed to user uploaded file <= 500 KB
            };
            // Was a subfolder selected in Home Index page?
            if (!string.IsNullOrEmpty(subFolder))
            {
                root.StartPath = new DirectoryInfo(Server.MapPath("~/" + folder + "/" + subFolder));
            }
            driver.AddRoot(root);
            var connector = new Connector(driver);
            return connector.Process(HttpContext.Request);
        }

        public virtual ActionResult SelectFile(string target)
        {
            FileSystemDriver driver = new FileSystemDriver();
            driver.AddRoot(
                new Root(
                    new DirectoryInfo(Server.MapPath("~/")),
                    "http://" + Request.Url.Authority + "/")
                { IsReadOnly = false });
            var connector = new Connector(driver);
            return Json(connector.GetFileByHash(target).FullName);
        }
    }
}

TMS/TMS/Presentation/Panel/Areas/Kullanici/Controllers/FileManagerController.cs
using TMS.View.Genel;
using System.Web.Mvc;

namespace TMS.Panel.Web.Areas.Kullanici.Controllers
{
    public class FileManagerController : Controller
    {
        public virtual ActionResult Index()
        {
            TMS.Panel.Web.Code.Security.CustomPrincipal Usr = (User as TMS.Panel.Web.Code.Security.CustomPrincipal);
            FileViewModel model = new FileViewModel() { Folder = Usr.Folder, SubFolder = Usr.SubFolder };
            return View(model);
        }
    }
}

TMS/TMS/Presentation/Panel/Areas/Kullanici/Views/Kullanici/Index.cshtml
@model TMS.View.Kullanici.Anasayfa
@{
    ViewBag.Title = "Kullanici";
    Layout = "~/Areas/Kullanici/Views/Shared/_Layout.cshtml";
}
<header class="page-header">
    <h2>Token Yönetim Sistemi</h2>
    <div class="right-wrapper pull-right">
        <ol class="breadcrumbs">
            <li>
                <a href="~/Kullanici/Anasayfa/Index">
                    <i class="fa fa-home"></i>
                </a>
            </li>
            <li><span>Kullanici</span></li>
        </ol>
        @*<a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fa fa-chevron-left"></i></a>*@
    </div>
</header>
@using (Html.BeginForm("IslemYap", "Anasayfa", FormMethod.Post, null))
{
    <div class="row">
        <div class="clearfix"></div>
        <div class="col-md-12 ">
            @Html.Partial("_KullaniciBilgileri", Model.User)
        </div>
    </div>
}
@section LayoutScript{
    @Html.Partial("_MesajSistemi", Model.IslemMesaj)
}

TMS/TMS/Presentation/Panel/Areas/Kullanici/Views/Kullanici/Profil.cshtml
@model TMS.View.Kullanici.Profil
@using TMS.Core.Lib;
@{
    ViewBag.Title = "Profil";
    Layout = "~/Areas/Kullanici/Views/Shared/_Layout.cshtml";
}
<div class="col-md-12 col-sm-12 col-xs-12">
    <header class="page-header">
        <h2>Profil Güncelleme İşlemleri</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="~/Kullanici/Anasayfa/Index">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Profil İşlemleri</span></li>
            </ol>
        </div>
    </header>
</div>
<div class="col-md-12 col-sm-12 col-xs-12">
    <section class="panel">
        @using (Html.BeginForm("Profil", "Kullanici", FormMethod.Post, new { @class = "form-horizontal form-bordered", @id = "FrmIslem" }))
        {
            TMS.Panel.Web.Code.Security.CustomPrincipal Usr = (HttpContext.Current.User as TMS.Panel.Web.Code.Security.CustomPrincipal);
            @Html.AntiForgeryToken()
            @Html.HiddenFor(x => x.AktifKayit.No)
            @Html.HiddenFor(x => x.AktifKayit.Resim)
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-9 col-xs-12 ">
                        <div class="form-group">
                            <div class="col-md-4 text-right MarginTop5">
                                @Html.LabelFor(x => x.AktifKayit.Ad) <span class="required">*</span>
                            </div>
                            <div class="col-md-8">
                                @Html.TextBoxFor(x => x.AktifKayit.Ad, new { @class = "form-control" })
                                @Html.HiddenFor(x => x.AktifKayit.Ad)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 text-right MarginTop5">
                                @Html.LabelFor(x => x.AktifKayit.Soyad) <span class="required">*</span>
                            </div>
                            <div class="col-md-8">
                                @Html.TextBoxFor(x => x.AktifKayit.Soyad, new { @class = "form-control" })
                                @Html.HiddenFor(x => x.AktifKayit.Soyad)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 text-right MarginTop5">
                                @Html.LabelFor(x => x.AktifKayit.Telefon) <span class="required">*</span>
                            </div>
                            <div class="col-md-8">
                                @Html.TextBoxFor(x => x.AktifKayit.Telefon, new { @class = "form-control" })
                                @Html.HiddenFor(x => x.AktifKayit.Telefon)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-4 text-right MarginTop5">
                                @Html.LabelFor(x => x.AktifKayit.Resim)
                            </div>
                            <div class="col-md-4">
                                <img style="border-top-left-radius:5px;border-top-right-radius:5px;" id="ImgRsmAktifKayit_Resim" width="200" height="200"
                                     src="@TMS.Panel.Web.Araclar.HtmlHelpers.ResolveServerUrl(string.Format("{0}?h=200&w=200&mode=max&scale=both",Model.AktifKayit.Resim),false)" />
                                @{
                                    TMS.View.Genel.DosyaSecim DosyaFotoSecim = new TMS.View.Genel.DosyaSecim();
                                    DosyaFotoSecim.Deger = Model.AktifKayit.Resim;
                                    DosyaFotoSecim.Baslik = "Dosya";
                                    DosyaFotoSecim.StateKontrolId = string.Format("ImgRsm{0}", Html.NameFor(x => x.AktifKayit.Resim).ToString().Replace(".", "_"));
                                    DosyaFotoSecim.HedefKontrolId = "AktifKayit_Resim";
                                    DosyaFotoSecim.LabelClass = "col-md-1 MarginTop5";
                                    DosyaFotoSecim.ControlClass = "col-md-6";
                                    Html.RenderPartial("_FotoSecim", DosyaFotoSecim);
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="panel-footer " id="PnlDegerlendirmeAraclar">
                <div class="form-group col-md-9 col-xs-12 ">
                    <div class="col-md-8  MarginTop5 col-sm-12">
                    </div>
                    <div class="col-md-4 col-sm-12">
                        <div class="pull-right">
                            <span class="btn btn-success btn-sm" id="btn-degerlendirme-cevap-kaydet" style="margin-left:5px;">
                                <i class="fa fa-save"></i>
                                <input type="submit" class="tlbtn" name="BtnIslem" value="Kaydet" />
                            </span>
                            <span class="btn btn-danger btn-sm" id="btn-degerlendirme-cevap-iptalet" style="margin-left:5px;">
                                <i class="fa fa-close"></i>
                                <input type="submit" class="tlbtn" name="BtnIslem" value="İptal Et" />
                            </span>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
            </footer>
        }
    </section>
</div>
@section LayoutScript{
    @Html.Partial("_MesajSistemi", Model.IslemMesaj)
    <script type="text/javascript">
        $(document).ready(function () {

        });
    </script>
}