TMS/TMS/Presentation/Panel/Areas/Administrator/Controllers/GenelAyarController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TMS.Core.Data;
using TMS.Core.Service;

namespace TMS.Panel.Web.Areas.Administrator.Controllers
{
    public class GenelAyarController : AdministratorBaseController
    {
        #region --# Servis Tanımları

        private readonly GenelAyarService GenelAyarService = new GenelAyarService();

        #endregion --# Servis Tanımları

        // GET: Administrator/Ayarlar
        public ActionResult Index()
        {
            TMS.View.Administrator.GenelAyar Model = new TMS.View.Administrator.GenelAyar();
            Model.AyarListesi = GenelAyarService.GetAll().ToList();
            return View(Model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(TMS.View.Administrator.GenelAyar Model, FormCollection Form)
        {
            switch (Request.Form["BtnIslem"])
            {
                case "Kaydet":
                    {
                        List<string> KeyListesi = new List<string>();
                        foreach (var Item in Form)
                        {
                            if (Item.ToString() != "BtnIslem")
                            {
                                string SystemAd = Item.ToString();
                                string Deger = Form[SystemAd].ToString();
                                Core.Data.GenelAyar GenelAyar = GenelAyarService.Get(x => x.SystemAd == SystemAd);
                                if (GenelAyar == null)
                                {
                                    GenelAyar = new Core.Data.GenelAyar()
                                    {
                                        SystemAd = SystemAd,
                                        Deger = Deger
                                    };
                                    GenelAyarService.Add(GenelAyar);
                                }
                                else
                                {
                                    GenelAyar.Deger = Deger;
                                    GenelAyarService.Update(GenelAyar);
                                }
                                GenelAyarService.Commit();
                                KeyListesi.Add(SystemAd);
                            }
                        }

                        List<Core.Data.GenelAyar> SilinecekAyarlar = GenelAyarService.GetMany(x => !KeyListesi.Contains(x.SystemAd)).ToList();
                        foreach (var SilGenelAyar in SilinecekAyarlar)
                        {
                            GenelAyarService.Delete(SilGenelAyar);
                        }
                        GenelAyarService.Commit();
                        Model.AyarListesi = GenelAyarService.GetAll().ToList();
                        break;
                    }
                default:
                    break;
            }
            return View(Model);
        }
    }
}

TMS/TMS/Presentation/Panel/Areas/Administrator/Views/GenelAyar/Index.cshtml
@model TMS.View.Administrator.GenelAyar
@{
    ViewBag.Title = "Genel Ayarlar";
    Layout = "~/Areas/Administrator/Views/Shared/_Layout.cshtml";
}
@using System.Collections;
@using System.Linq;
@using System.Runtime;
<div class="col-md-12 col-sm-12 col-xs-12">
    <header class="page-header page-header-custom-background">
        <h2>Genel Ayarlar İşlemleri</h2>
        <div class="right-wrapper pull-right">
            <ol class="breadcrumbs">
                <li>
                    <a href="~/Administrator/Anasayfa/Index">
                        <i class="fa fa-home"></i>
                    </a>
                </li>
                <li><span>Genel Ayarlar</span></li>
            </ol>
        </div>
    </header>
</div>
@using (Html.BeginForm("Index", "GenelAyar", FormMethod.Post, new { @id = "FrmIslemMain" }))
{
    Html.AntiForgeryToken();
    <div class="col-md-12 col-sm-12 col-xs-12" data-plugin-portlet id="portlet-1">
        <section class="panel panel-info" id="panel-1" data-portlet-item>
            <header class="panel-heading portlet-handler clearfix">
                <div class="btn-group pull-right">
                    <span class="btn btn-success" style="margin-left:5px;">
                        <i class="fa fa-save"></i>
                        <input type="submit" name="BtnIslem" value="Kaydet" />
                    </span>
                    <span class="btn btn-danger " style="margin-left:5px;">
                        <i class="fa fa-close"></i>
                        <input type="submit" name="BtnIslem" value="İptal Et" />
                    </span>
                </div>
                <div class="btn-group pull-left">
                    <h2 class="panel-title">Ayarlar</h2>
                </div>
            </header>
            <div class="panel-body">
                <section class="panel panel-info" id="panel-1" data-portlet-item>
                    <header class="panel-heading portlet-handler clearfix">
                        <div class="btn-group pull-right">

                        </div>
                        <div class="btn-group pull-left">
                            <h2 class="panel-title">Sözleşme ve Kurumsal Kimlik Ayarları </h2>
                            <label> </label>
                        </div>
                    </header>
                    <div class="panel-body">
                        <div class="col-md-9 col-xs-12 mb-sm-12">
                            <div class="form-group">
                                <div class="col-md-12  MarginTop5">
                                    <label>Kullanıcı Sözleşmesi Metni</label>
                                </div>
                                <div class="col-md-12">
                                    <textarea class="form-control col-md-12 summernote" type="text" name="TMSKullanıciSozlezmesi">
                                        @(Model.AyarListesi.Where(x=>x.SystemAd=="TMSKullanıciSozlezmesi").FirstOrDefault()==null?"":Model.AyarListesi.Where(x=>x.SystemAd=="TMSKullanıciSozlezmesi").FirstOrDefault().Deger)
                                    </textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </section>
    </div>
}
@section LayoutScript{
    @Html.Partial("_MesajSistemi", Model.IslemMesaj)
}